# Generated by Django 5.1 on 2024-12-27 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='assigned_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='realestate.employee'),
        ),
        migrations.AlterField(
            model_name='broker',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
